### ISSUE TITLE
Verification email link cseréje

### ISSUE THREAD

**Issue by pakaikarolina** [flowacademyhu/iota-vajdasag-brand#107]
A keycloak által generált emailben a link ne a localhostra vigye a usert, hanem a stagingen is tudjon működni

**Comment by borosr** [comment]
Várunk választ itt is: https://stackoverflow.com/questions/66399005/keycloak-configuration-http-link-in-verify-email

**Comment by pakaikarolina** [comment]
@borosr Mivel a stagingen futó keycloakban a staginges link megy ki, ezt talán be lehet már zárni, nem?

**Comment by ImreTheFifth** [comment]
@borosr zártuk, mivel most stagingen staginges link megy ki. Nyisd újra pls, ha nem értesz egyet ezzel
