### ISSUE TITLE
Egy adott cég összes termékének listázása 

### ISSUE THREAD

**Issue by ttiborgh** [flowacademyhu/iota-vajdasag-brand#109]
Végpont létrehozása ItemControllerben, amely az adott cég összes termékét visszaadja FE számára List<CegAdminDTO> formátumban. Megoldás módja: mentorokkal egyeztetve.

**Comment by borosr** [comment]
> az adott cég összes termékét visszaadja
Egy adott cég termékeit jelenleg egy felhasználó tudja kezelni, igaz? Mert ebben az esetben elég lenne az item ownerId-ja alapján megvalósítani a szűrést.
Amennyiben egy céghez több felhasználó is tud terméket rendelni, úgy nagyobb változtatást igényel a feladat megoldás - be kell vezetni a céget mint entitást. 
@sandorforgo melyik irány tükrözi a követelményeket?

**Comment by sandorforgo** [comment]
Egy adott cég termékeit jelenleg egy felhasználó tudja kezelni, igaz?  - Igaz, és ez a követelmény is. Egy cég - egy felhasználó (plusz természetesen a Superadmin, aki mindent)
