### ISSUE TITLE
Termékadatok lokalizációja

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-vajdasag-brand#16]
A termék létrehozása és szerkesztése oldalon legyen a formon belül egy nyelvválasztó, ami a termék adatainak a fordítását segíti elő.
Alapértelmezetten a felhasználó aktuális nyelvét válasszuk ki a formban, tehát azt, amilyen nyelven használja az admint.
Ha vált nyelvet, akkor a fordítandó mező adott nyelvhez tartozó értékét jelenítsük meg és szerkesszük. A legtöbb mezőt nem kell fordítani, csak a következőket kell:

- leírás
- cím
- weboldal

### Acceptance criteria
Mentésnél az összes fordított adatot mentsük el.

**Comment by pakaikarolina** [comment]
https://github.com/flowacademyhu/iota-vajdasag-brand/issues/85
