### ISSUE TITLE
Cégregisztráció deaktiválása

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-vajdasag-brand#20]
A superadmin deaktiválni tudja egy aktivált cég regisztrációját. Ezt a felhasználólistában tudja megtenni, a már jóváhagyott felhasználók sorában legyen egy deaktiválás ikon, amit megnyomva az API-n keresztül deaktiváljuk a regisztrációt.

### Acceptance criteria
Csak a már jóváhagyott felhasználók sorában van ilyen ikon és megnyomásra működik a fent leírt módon.

**Comment by ImreTheFifth** [comment]
Jelenleg soft delete/deaktiválás a törlés funkciónk. Ennek átalakítását fejlesztési területnek definiáltuk.
