### ISSUE TITLE
Felhasználók listázása

### ISSUE THREAD

**Issue by borosr** [flowacademyhu/iota-vajdasag-brand#27]
Legyen egy endpoint ami az eltárolt user-eket adja vissza egy listában.
- Az endpoint csak authentikáció után legyen elérhető és csak `SUPERADMIN` szerepkörű felhasználóknak.
- A lista legyen rendezett, alapértelmezetten a regisztráció időpontja szerint, de legyen megadható query paramként is opcionálisan, `order_by` névvel és String értékkel, ami egyelőre állítsa közvetlenül a lekérdezés ORDER BY értékét.
- Paging legyen elérhető page és limit értékekkel

**Comment by ImreTheFifth** [comment]
https://github.com/flowacademyhu/iota-vajdasag-brand/pull/65
