### ISSUE TITLE
Felhasználó törlése

### ISSUE THREAD

**Issue by borosr** [flowacademyhu/iota-vajdasag-brand#29]
Legyen egy endpoint, ami path variable-ként várja a felhasználó ID-ját és inaktiválja azt a Keycloakban, érdemes a statust az adatbázisban is ábrázolni, hogy egyértelmű legyen.

**Comment by ImreTheFifth** [comment]
pr: https://github.com/flowacademyhu/iota-vajdasag-brand/pull/61
