### ISSUE TITLE
Nyelvi fájl frissítése 

### ISSUE THREAD

**Issue by sandorforgo** [flowacademyhu/iota-vajdasag-brand#47]
A hivatkozott fordítások alapján az oldalon lévő szövegek frissítése. Itt a fájl: https://1drv.ms/x/s!AkdqOQYWitVpmrF3C_h6cWR5mW5JRg?e=Rm6FNJ

**Comment by borosr** [comment]
Backenden egyelőre nincsenek nyelvi állományok, nem inkább frontend?
