### ISSUE TITLE
Regisztrációs oldal

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/iota-vajdasag-brand#6]
A login oldalon legyen egy "Regisztrálok" gomb, amit ha megnyom, akkor egy regisztrációs oldalra jut.
A regisztrációhoz a következő adatok kell megadnia a felhasználónak:
- név
- magánszemély vagy jogi személy (dropdown vagy radio)
- adószám (csak jogi személy esetén jelenítsük meg)
- lakcím/székhely
- email cím
- jelszó
- jelszó még egyszer
- ÁSZF és Privacy Policy elfogadó checkbox (kötelező bekattintani a regisztrációhoz)
- Regisztráció gomb

A form alján legyen egy elválasztó vonal és egy szöveg: "Regisztráltál már?"
Ezalatt legyen egy gomb, ami visszanavigál a login oldalra a következő szöveggel: "Belépés"

A sikeres regisztrálás után jelenítsünk meg egy tájékoztató üzenetet, hogy a regisztráció sikerült és a jóváhagyás folyamatban van.
API hiba esetén jelenítsünk meg egy üzenetet, hogy nem sikerült regisztrálni.

### Acceptance criteria
A fent leírt módon jelenik meg a form, minden mező kötelező, kivéve az adószám, az csak jogi személy esetén az. Az összes mezőt validáljuk értelemszerűen (email legyen email cím, jelszó kritériumok teljesüljenek stb.).
Amennyiben a backend még nem áll készen, akkor egy dummy regisztráció legyen mockolt API-val.

**Comment by pakaikarolina** [comment]
@6uliver a validáció mit takar? Leginkább a jelszóra gondolok itt
Illetve az ÁSZF és a PP gondolom link kell hogy legyenek, ahhoz akkor kellene elérési útvonal

**Comment by SiposGergo** [comment]
@pakaikarolina 
A jelszó validálásnál olyanra gondolj, hogy pl.: kell bele minimum 2 darab nagybetű és 2 szám.
A pontos validációs feltételeket a PM-el kellene egyeztetni, ahogy linkeket is ő tud majd adni. 
@sandorforgo

**Comment by pakaikarolina** [comment]
Köszi Gergő, igen ilyenre gondoltam, csak pontosabb kritériumokat szeretnék kérni :)

**Comment by sandorforgo** [comment]
@pakaikarolina Szia, jelszókövetelmények:
legalább 8 karakter;
legalább egy nagybetű és egy kisbetű;
legalább egy szám;
szóközt nem tartalmazhat;
érvényes egyéb karakterek:~ ! ? @ # $ % ^ & * _ - + ( ) [ ] { } > < / \ | " ' . , : ;

**Comment by sandorforgo** [comment]
Adatkezelési: https://jusoft.hu/docs/Adatkezelesi%20tajekoztato_Jusoft.pdf
ÁSZF: https://jusoft.hu/docs/ASZF_adatfeldolgozoi_tevekenyseghez.pdf
