### ISSUE TITLE
A nyelvválasztókban a cirill karakterek latin betűsre cserélése

### ISSUE THREAD

**Issue by sandorforgo** [flowacademyhu/iota-vajdasag-brand#78]
A nyelvválasztókban jelenleg a szerb nyelv így van írva: Српски 
És így kérte az ügyfél: Srpski
Legyen az ügyfél által kért formában.

**Comment by borosr** [comment]
Ez megfelelhet a célnak: https://github.com/kukicmilorad/cyrlat
A dependency-ként betöltéshez pedig ez lehet jó: https://jitpack.io/

**Comment by ImreTheFifth** [comment]
A nyelvválasztóban úgy nézem, hogy a kért 'Srpski' text van, mint ahogy ez a ticket kéri. 
@borosr  a fentiek miatt zárom ezt a ticketet, ha esetleg mégse kéne, szólj kérlek és újranyitom. Köszi!
