### ISSUE TITLE
Termék nyelvesítése

### ISSUE THREAD

**Issue by borosr** [flowacademyhu/iota-vajdasag-brand#85]
Bővítsük ki a terméket leíró osztályokat egy language Enummal, ami `hu,en,rs` értékeket tárol. 

- [ ] Amennyiben nincs megadva, legyen az alapértelmezett a Magyar nyelv. 
- [ ] Szerb nyelvnél pedig minden esetben konvertáljuk a ciril betűket latinokká

**Comment by pakaikarolina** [comment]
https://github.com/flowacademyhu/iota-vajdasag-brand/issues/16

**Comment by borosr** [comment]
#78
